import EventsContextProvider from "@/context/EventsContext";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Calender App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <EventsContextProvider>
          {children}
          <Toaster position="top-center" reverseOrder={false} />
        </EventsContextProvider>
      </body>
    </html>
  );
}
